# Site settings
title: VPSがオオアリクイに殺されて1週間が過ぎました
email: syun@ikejima.org
description: > # this means to ignore newlines until "baseurl:"
  メインのBlogが置いてあったVPSが音信不通になったので、しばらくの避難所
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ikeji.github.io" # the base hostname & protocol for your site
twitter_username: ikeji
github_username:  ikeji

# Build settings
markdown: kramdown
