# Site settings
title: ikejiのblog (VPSがオオアリクイに殺されて1ヶ月が過ぎました)
email: syun@ikejima.org
description: >
  メインのBlogが置いてあったVPSが音信不通になったので、移転しました。ドメインはそのうちかえます。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ikeji.github.io" # the base hostname & protocol for your site
twitter_username: ikeji
github_username:  ikeji

# Build settings
markdown: kramdown
